# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.244.0
        with:
#          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - run: >-
          curl -i -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Setup Yarn
        id: yarn
        uses: bahmutov/npm-install@v1.10.9
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: gulp build
        env:
          JEKYLL_ENV: production
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JEKYLL_BASE_URL: ${{ steps.pages.outputs.base_path }}
      - name: Upload artifact
        id: upload_artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages-${{ github.run_number }}-${{ github.run_attempt }}
    outputs:
      artifact_id: ${{ steps.upload_artifact.outputs.artifact_id }}
      artifact_name: github-pages-${{ github.run_number }}-${{ github.run_attempt }}

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: >-
          curl -i -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: ${{ needs.build.outputs.artifact_name }}
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}

